services:
  - type: web
    name: chat-openai-playwright
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python server.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
